#!/usr/bin/env bash
# Installs Nginx with the following configurations:
#+    Listens on port 80.

mkdir /etc/nginx/html
sudo echo "Hello World" > /etc/nginx/html/index.html
sudo echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

sudo service nginx restart
